import { DEFAULT_LOCALE, type Locale } from '@/i18n';

const hintsEn: Record<string, string> = {
  motd: 'Message of the day shown in the Minecraft server list.',
  pvp: 'Whether players can damage each other.',
  difficulty: 'World difficulty: peaceful, easy, normal, or hard.',
  gamemode: 'Default game mode for new players: survival, creative, adventure, or spectator.',
  'max-players': 'Maximum number of players allowed on the server at once.',
  'online-mode': 'If true, only authenticated (premium) accounts can join.',
  'white-list': 'If true, only players on the whitelist can join.',
  'spawn-monsters': 'Whether hostile mobs spawn in the world.',
  'spawn-animals': 'Whether passive mobs spawn in the world.',
  'view-distance': 'How many chunks around each player are sent to clients (2–32).',
  'simulation-distance': 'How many chunks around players stay loaded and tick (3–32).',
  'level-seed': 'Seed used when generating a new world; leave empty for random.',
  'level-name': 'Folder name of the world save (default: world).',
  'enable-command-block': 'Whether command blocks are enabled on the server.',
  hardcore: 'If true, players are banned on death and difficulty is locked to hard.',
  'spawn-protection': 'Radius around spawn where only ops can break blocks (0 disables).',
  'max-world-size': 'Maximum world border radius in blocks.',
  'allow-flight': 'Whether players in survival/adventure may fly (anti-cheat related).',
  'server-port': 'TCP port the server listens on (default 25565).',
  'server-ip': 'Network interface to bind; leave empty to listen on all addresses.',
  'allow-nether': 'Whether players can travel to the Nether dimension.',
  'generate-structures': 'Whether villages, strongholds, and other structures generate.',
  'force-gamemode': 'If true, players are forced into the default gamemode on join.',
  'player-idle-timeout': 'Minutes before an idle player is kicked (0 disables).',
  'network-compression-threshold': 'Packet size above which traffic is compressed (-1 disables).',
  'enable-rcon': 'Enables remote console (RCON) access.',
  'rcon.port': 'TCP port for RCON connections.',
  'rcon.password': 'Password required for RCON access.',
  'enable-query': 'Enables GameSpy4 query protocol for server list tools.',
  'query.port': 'UDP port for query responses (defaults to server-port).',
  'enforce-whitelist': 'If true, whitelist is enforced even when white-list is off.',
  'hide-online-players': 'If true, the player count is hidden in the server list.',
  'op-permission-level': 'Permission level granted to server operators (1–4).',
  'rate-limit': 'Maximum packets per second a client may send (0 disables).',
  'sync-chunk-writes': 'If true, chunk data is saved synchronously (safer, slower).',
  'prevent-proxy-connections': 'If true, blocks connections via proxy/VPN services.',
  'resource-pack': 'URL of a resource pack offered to joining players.',
  'require-resource-pack': 'If true, players must accept the resource pack to join.',
  'entity-broadcast-range-percentage': 'Percentage of default entity tracking range (10–1000).',
  'max-tick-time': 'Milliseconds per tick before the watchdog stops the server.',
  'pause-when-empty-seconds': 'Seconds after the last player leaves before the server pauses.',
};

const hintsRu: Record<string, string> = {
  motd: 'Сообщение дня, отображаемое в списке серверов в клиенте Minecraft.',
  pvp: 'Разрешён ли урон между игроками.',
  difficulty: 'Сложность мира: peaceful, easy, normal или hard.',
  gamemode: 'Режим игры по умолчанию для новых игроков: survival, creative, adventure или spectator.',
  'max-players': 'Максимальное число игроков на сервере одновременно.',
  'online-mode': 'Если true, подключаться могут только лицензионные аккаунты.',
  'white-list': 'Если true, подключаться могут только игроки из белого списка.',
  'spawn-monsters': 'Появляются ли враждебные мобы в мире.',
  'spawn-animals': 'Появляются ли мирные мобы в мире.',
  'view-distance': 'Сколько чанков вокруг игрока отправляется клиенту (2–32).',
  'simulation-distance': 'Сколько чанков вокруг игрока загружено и обрабатывается (3–32).',
  'level-seed': 'Сид для генерации мира; пустое значение — случайный сид.',
  'level-name': 'Имя папки мира (по умолчанию: world).',
  'enable-command-block': 'Разрешены ли командные блоки на сервере.',
  hardcore: 'Если true, при смерти игрок банится, сложность фиксируется на hard.',
  'spawn-protection': 'Радиус вокруг спавна, где ломать блоки могут только операторы (0 — выкл.).',
  'max-world-size': 'Максимальный радиус границы мира в блоках.',
  'allow-flight': 'Разрешён ли полёт в survival/adventure (связано с античитом).',
  'server-port': 'TCP-порт, на котором слушает сервер (по умолчанию 25565).',
  'server-ip': 'Сетевой интерфейс для привязки; пусто — все адреса.',
  'allow-nether': 'Разрешён ли переход в измерение Нижний мир.',
  'generate-structures': 'Генерируются ли деревни, крепости и другие структуры.',
  'force-gamemode': 'Если true, игроки принудительно переводятся в gamemode по умолчанию.',
  'player-idle-timeout': 'Минут бездействия до кика (0 — отключено).',
  'network-compression-threshold': 'Размер пакета, выше которого включается сжатие (-1 — выкл.).',
  'enable-rcon': 'Включает удалённую консоль (RCON).',
  'rcon.port': 'TCP-порт для подключений RCON.',
  'rcon.password': 'Пароль для доступа по RCON.',
  'enable-query': 'Включает протокол GameSpy4 query для мониторинга сервера.',
  'query.port': 'UDP-порт для query-ответов (по умолчанию совпадает с server-port).',
  'enforce-whitelist': 'Если true, белый список применяется даже при white-list=false.',
  'hide-online-players': 'Если true, число игроков скрыто в списке серверов.',
  'op-permission-level': 'Уровень прав операторов сервера (1–4).',
  'rate-limit': 'Максимум пакетов в секунду от клиента (0 — без ограничения).',
  'sync-chunk-writes': 'Если true, чанки сохраняются синхронно (надёжнее, медленнее).',
  'prevent-proxy-connections': 'Если true, блокирует подключения через прокси/VPN.',
  'resource-pack': 'URL ресурспака, предлагаемого игрокам при входе.',
  'require-resource-pack': 'Если true, для входа нужно принять ресурспак.',
  'entity-broadcast-range-percentage': 'Процент стандартной дальности отслеживания сущностей (10–1000).',
  'max-tick-time': 'Миллисекунд на тик, после чего watchdog останавливает сервер.',
  'pause-when-empty-seconds': 'Секунд после выхода последнего игрока до паузы сервера.',
};

const hintsByLocale: Record<Locale, Record<string, string>> = {
  en: hintsEn,
  ru: hintsRu,
};

export function getServerPropertyHint(locale: Locale, key: string): string | undefined {
  return hintsByLocale[locale]?.[key] ?? hintsByLocale[DEFAULT_LOCALE]?.[key];
}
