include /etc/nginx/gzip.conf;

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /downloads/ {
        add_header Content-Disposition 'attachment';
        try_files $uri =404;
    }

    location ^~ /.well-known/ {
        try_files $uri =404;
    }

    location /assets/ {
        gzip_static on;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location = /index.html {
        gzip_static on;
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location / {
        gzip_static on;
        try_files $uri $uri/ /index.html;
    }
}
